export const ErrorCategory = {
  NETWORK_ERROR: "NETWORK_ERROR",
  TIMEOUT: "TIMEOUT",
  HTTP_ERROR: "HTTP_ERROR",
  ROBOTS_BLOCKED: "ROBOTS_BLOCKED",
  RATE_LIMITED: "RATE_LIMITED",
  INVALID_URL: "INVALID_URL",
  UNSUPPORTED_CONTENT: "UNSUPPORTED_CONTENT",
  PAGE_TOO_LARGE: "PAGE_TOO_LARGE",
  PARSE_ERROR: "PARSE_ERROR",
  SSRF_BLOCKED: "SSRF_BLOCKED",
  CANCELLED: "CANCELLED",
  UNKNOWN: "UNKNOWN",
} as const

export type ErrorCategory = (typeof ErrorCategory)[keyof typeof ErrorCategory]